apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: trucking-delivery-status-papi
  name: trucking-delivery-status-papi
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trucking-delivery-status-papi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: trucking-delivery-status-papi
    spec:
      containers:
      - image: mjubilee/bcm-trucking-delivery-status-papi:0.0.1
        imagePullPolicy: IfNotPresent
        name: trucking-delivery-status-papi-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trucking-delivery-status-papi
  name: trucking-delivery-status-papi
  namespace: default
spec:
  ports:
  - port: 8000text
  
    protocol: TCP
    targetPort: 8000
  selector:
    app: trucking-delivery-status-papi
  sessionAffinity: None
  type: LoadBalancer
